name: Feature CI

on:
  push:
    branches:
    - feature/*
  pull_request:
    types: [opened]

  workflow_dispatch: 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Changing gradlew permission
        run: chmod +x ./gradlew

      - name: Run build
        run: ./gradlew build

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Changing gradlew permission
        run: chmod +x ./gradlew

      - name: Run unit
        run: ./gradlew test

